/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DolarRouteImport } from './routes/dolar'
import { Route as EuroRouteImport } from './routes/euro'
import { Route as ResumoRouteImport } from './routes/resumo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DolarRoute = DolarRouteImport.update({
  id: '/dolar',
  path: '/dolar',
  getParentRoute: () => rootRouteImport,
} as any)
const EuroRoute = EuroRouteImport.update({
  id: '/euro',
  path: '/euro',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumoRoute = ResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dolar': typeof DolarRoute
  '/euro': typeof EuroRoute
  '/resumo': typeof ResumoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dolar': typeof DolarRoute
  '/euro': typeof EuroRoute
  '/resumo': typeof ResumoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dolar': typeof DolarRoute
  '/euro': typeof EuroRoute
  '/resumo': typeof ResumoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dolar' | '/euro' | '/resumo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dolar' | '/euro' | '/resumo'
  id: '__root__' | '/' | '/dolar' | '/euro' | '/resumo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DolarRoute: typeof DolarRoute
  EuroRoute: typeof EuroRoute
  ResumoRoute: typeof ResumoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dolar': {
      id: '/dolar'
      path: '/dolar'
      fullPath: '/dolar'
      preLoaderRoute: typeof DolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/euro': {
      id: '/euro'
      path: '/euro'
      fullPath: '/euro'
      preLoaderRoute: typeof EuroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumo': {
      id: '/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof ResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DolarRoute: DolarRoute,
  EuroRoute: EuroRoute,
  ResumoRoute: ResumoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
